### PR TITLE
Show preview URL on GitHub PullRquest page ( fix #55 )

### LINKED ISSUE #55: CIがAWSにpushしたプレビューページへのリンク探すのが面倒
travisの吐くログを探せば
https://travis-ci.org/ntt-developers/ntt-tech-conference-01/builds/191513418
からは
http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/0b3cfd7204e53620acef741562dd744986c14d2e/index.html
を拾ってこれるんだけど、Pull-Requestの画面にtravisから直接発言して欲しいと思わない？

### PR DESCRIPTION
**Pull request by hisaharu**

### CODE REVIEW

**Comment by hisaharu** [comment]
> ERROR:  Error installing github_api:
> 	rack requires Ruby version >= 2.2.2.

**Comment by hisaharu** [comment]
Travisェ・・・
> The Ruby VM provides recent versions of:
> Ruby: 2.2.0, 2.1.x, 2.0.0, 1.9.3, 1.9.2 and 1.8.7
> JRuby: 1.7.x (1.8 and 1.9 mode)
> Ruby Enterprise Edition: 1.8.7 2012.02
https://docs.travis-ci.com/user/languages/ruby/

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/1c69ee42e2991b4dbb72504102a9a5560e393b18/

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/30444cdb4bbbb2760a05ba8b01a9c2fc73489b57/

**Comment by hisaharu** [comment]
だいたい完成したけど `TRAVIS_PULL_REQUEST` が ブランチ先端の commit ID と一致しないのが謎
https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

**Comment by hisaharu** [comment]
PullReq の場合の `TRAVIS_COMMIT` は `head`.`sha` ではなく `merge_commit_sha` ということらしい
https://api.github.com/repos/ntt-developers/ntt-tech-conference-01/pulls/68

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/be0969ca287cff2c396abff74eba2d2afc141e04/

**Comment by ykubota** [comment]
LGTM, thanks!

**Pull request merged**
