### PR TITLE
added author's info to showcase.slim

### PR DESCRIPTION
**Pull request by homelith**
devo preview me

### CODE REVIEW

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/b22a060dff86440e8577545c476d460480a83105/

**Comment by hisaharu** [comment]
LGTM

**Comment by ykubota** [comment]
We should wait a merging, because this author wants reviews by presenters of showcases.

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/ec4b5385223a74ad1a93c0ca76bdc8141a60ee58/

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/9c162fa49ab7d8b01b3c6f3e13e22fa29d80034f/

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/c553ec99c62c6da8bf7f2c4fe4f03e9191897d09/

**Comment by JunichiWatanuki** [comment]
ご配慮いただき、ありがとうございます。

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/c553ec99c62c6da8bf7f2c4fe4f03e9191897d09/

**Comment by homelith** [comment]
all presenters appeared in program confirmed the preview, now request for merge.

**Comment by homelith** [comment]
PR closed by mistake, then reopen

**Comment by mikakadevo2** [comment]
Preview: http://ntt-tech-conference-01.s3-website-ap-northeast-1.amazonaws.com/4011b3a53c9fee28028f727b5f3204b8fc450353/

**Comment by hisaharu** [comment]
LGTM

**Comment by aajisaka** [comment]
LGTM

**Pull request merged**
